"""MIKASA: the half that makes the numbers — oracle protocol, solver, sweep.

Imports `utils.mikasa` (what it takes to run a task); never the reverse.
Generated by mikasa/tools/publish_to_fork.py.
"""
